
server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/civicpulse_db
    username: civicpulse
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

